### ISSUE TITLE
Get tests passing in v1.0

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/diffeqr#12]
Hey @Non-Contradiction , can we get some help getting tests to pass on Julia v1.0? I'm not sure why it's saying devtools is missing now.

**Comment by Non-Contradiction** [comment]
Sue! What is the R version you are using? And what is the message?
devtools relies on Rtools, and I think there are some problems related to Rtools in R 3.5.1 or R 3.5.0 on windows.

**Comment by ChrisRackauckas** [comment]
I haven't been able to get it running locally so I am referring to our Travis and AppVeyor results:

https://travis-ci.org/JuliaDiffEq/diffeqr/jobs/462113215
