### ISSUE TITLE
Travis failures

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/diffeqr#2]
@Non-Contradiction did you have to do anything special to get Travis working?

**Comment by Non-Contradiction** [comment]
Every setup is written on the travis.yml. But I think since the latest version of `JuliaCall` is not on CRAN yet, which gets around julia #14577 by a trick, it is better to install the julia packages directly in the travis.yml and `using xxx` the packages to  make sure them get precompiled.

**Comment by Non-Contradiction** [comment]
For R packages, typically `library` function is not used, which is quite different to julia, and functions with package name like `JuliaCall::julia_assign` are used.

**Comment by ChrisRackauckas** [comment]
Thanks. I think I got it now. However, Travis is having a hard time finding `devtools`. Do you know what this is?

https://travis-ci.org/JuliaDiffEq/diffeqr/jobs/368913726#L1481

**Comment by Non-Contradiction** [comment]
It's a network failure. When such things happen, my "solution" is waiting for some time and then restart the test.

**Comment by ChrisRackauckas** [comment]
It looks like tests passed, but they were still red?

https://travis-ci.org/JuliaDiffEq/diffeqr/jobs/368959694#L2567

**Comment by Non-Contradiction** [comment]
The R language check requires all the parameters of exported functions to be documented, it seems that there are still some undocumented parameters?

**Comment by ChrisRackauckas** [comment]
Thanks! On to AppVeyor now! JuliaCall is great, nice work.

**Comment by Non-Contradiction** [comment]
DiffEq is great too!
By the way, I think it is better to use `Depends: R (>= 3.4.0)` instead of `Depends: R (>= 3.4.4)` in DESCRIPTION. `R 3.4.4` is only a bug-fixed version of `R 3.4.0` and everything should work with `R 3.4.0`. If `Depends: R (>= 3.4.4)` is used, then users with `R 3.4.0`, `R 3.4.1`, ... won't be able to install the package through CRAN.
