### ISSUE TITLE
Fixing the vignettes

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/diffeqr#9]
@Non-Contradiction noticed that the titles are off. 

https://github.com/JuliaDiffEq/diffeqr/blame/master/vignettes/ode.Rmd#L2

does that also have to be done here?

https://github.com/JuliaDiffEq/diffeqr/blame/master/vignettes/ode.Rmd#L7

I assumed that the system would handle this, i.e. replace with the title text.

Also, I thought it auto-captures the plots? I guess it might not be running because it's building on the CRAN server?

**Comment by Non-Contradiction** [comment]
Yes, it also has to be write in `%\VignetteIndexEntry`.

**Comment by Non-Contradiction** [comment]
The plots will be captured if the code is written in blocks like the first `setup` block
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
But not in the following blocks with that kind of format.

CRAN machines will also run the vignette code. So if you don't want it to run, you could use `knitr` to turn everything into plain md.

**Comment by ChrisRackauckas** [comment]
Cool. I just fixed up the markdown. Is it really not okay to put a patch in with the fixed vignettes until next month?

**Comment by Non-Contradiction** [comment]
I have submitted a patch onto CRAN for `convexjlr` within a month. It's okay if necessary, just add some explanation for the reason.

By the way, it seems that the pictures may be a little larger than CRAN's suggestions. On my mac, it says: 
"* checking installed package size ... NOTE
  installed size is  9.4Mb
  sub-directories of 1Mb or more:
    doc   9.3Mb"
And by doc, it means vignettes.
